import type { GetServerSideProps } from "next";
import React, { useState } from "react";
import { selectFolderState } from "</slices/folderSlice>";
import Head from "next/head";
import { useRouter } from "next/router";
import { AiOutlineArrowUp, AiOutlineInfoCircle } from "react-icons/ai";
import { FaFolder } from "react-icons/fa";
import { useSelector } from "react-redux";
import styled from "styled-components";
import { IoIosArrowForward, IoMdArrowDropdown } from "react-icons/io";
import { MdOutlineViewList } from "react-icons/md";
import { SlOptionsVertical } from "react-icons/sl";
import { EditFolderModal } from "</components/Ui/EditFolderModal>";

const DataGrid = styled.div`
  display: flex;
  align-items: center;
  margin-top: 30px;
  margin-bottom: 30px;
`;

const DataFile = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 30px;
  margin: 10px;
  min-width: 200px;
  border-radius: 5px;
  border: 0px solid;
  box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.75);
  cursor: pointer;
  svg {
    font-size: 20px;
    color: #1f1f1f;
  }
  p {
    font-size: 14px;
    overflow: hidden;
  }
`;

const DataListRow = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  p {
    display: flex;
    align-items: center;
    b {
      font-size: 16px;
      color: #444746;
      display: flex;
      align-items: center;
    }
    svg {
      font-size: 16px;
      margin: 10px;
      color: #1f1f1f;
    }
  }
`;
const DataHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid lightgray;
  .headerLeft {
    padding-left: 10px;
    display: flex;
    align-items: center;
    font-size: 24px;
    border-radius: 20px;
    &:hover {
      background: whitesmoke;
      cursor: pointer;
    }
  }
  .headerRight svg {
    margin: 0px 10px;
    font-size: 24px;
  }
`;
export default function Folder() {
  const [open, setOpen] = useState<boolean>(false);
  const [editId, setEditId] = useState<string>("");
  const handleOpen = () => {
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };
  const router = useRouter();
  const length = router.asPath?.split("/")?.length;
  const parentName = router.asPath
    ?.split("/")
    [length - 1]?.replaceAll("-", " ");
  const routes = router.asPath?.split("/");
  const allFolders = useSelector(selectFolderState);
  const folders = allFolders?.folders?.filter(
    (folder: any) => folder?.parentId === parentName
  );
  console.log(folders);
  return (
    <>
      <Head>
        <title>My Folder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DataHeader>
          <div className="headerLeft" onClick={() => router.push("/folder")}>
            <p>My folder</p>
            <IoIosArrowForward />
            {routes?.map((route: any, i) => (
              <>
                <p
                  // onClick={() => {
                  //   let st = "";
                  //   router.asPath.split("/").slice(0,i).map((r: any)=>)
                  //   router.push(`${router.asPath.split("/").slice(0,i)}`)
                  // }}
                >
                  {route?.replaceAll("-", " ")}
                </p>
                {route !== "" && i < length - 1 && <IoIosArrowForward />}
              </>
            ))}
            <IoMdArrowDropdown />
          </div>
          <div className="headerRight">
            <MdOutlineViewList />
            <AiOutlineInfoCircle />
          </div>
        </DataHeader>
        <div>
          <DataListRow>
            <p>
              <b>Folders</b>
            </p>
            <p>
              <b></b>
            </p>
            <p>
              <b></b>
            </p>
            <p>
              <b>
                Name <AiOutlineArrowUp />
              </b>
            </p>
          </DataListRow>
          <DataGrid>
          {open && (
              <EditFolderModal
                open={open}
                folderId={editId}
                handleOpen={handleOpen}
                handleClose={handleClose}
              />
            )}
            {folders?.map((folder: any) => (
              <DataFile key={folder?.id}>
                <FaFolder />
                <p onClick={() => router.push(folder?.path)}>{folder?.name}</p>
                <span
                  onClick={() => {
                    handleOpen(), setEditId(folder?.id);
                  }}
                >
                  <SlOptionsVertical />
                </span>
              </DataFile>
            ))}
          </DataGrid>
        </div>
        <div>
          <DataListRow>
            <p>
              <b>Files</b>
            </p>
          </DataListRow>
          <DataGrid>
            {/* { files.map(file => (
                        <DataFile key={file.id}>
                            <InsertDriveFileIcon />
                            <p>{file.data.filename}</p>
                        </DataFile>
                    ))} */}
          </DataGrid>
        </div>
      </div>
    </>
  );
}
