"use client";
import FolderData from '</components/FolderData/FolderData>';
import { IndexLayout } from '</components/layout/Layout>';
import Sidebar from '</components/layout/Sidebar>';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>My Drive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <Sidebar/>
        <FolderData/>
        </main>
    </>
  )
}
// Home.PageLayout = IndexLayout;